import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';
//import styles from './page.module.css';
import { Layout } from '@/layout/Layout';

const inter = Noto_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'My top',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Layout> {children}</Layout>
      </body>
    </html>
  );
}
