export const metadata = {
  title: 'Авторизация',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        {children}
        <div>Авторизация</div>
      </body>
    </html>
  );
}
